"""Update title field in PostView model

Revision ID: 018124a27859
Revises: c3f60658f41c
Create Date: 2024-07-31 16:38:18.248897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '018124a27859'
down_revision: Union[str, None] = 'c3f60658f41c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('farposts_preview', 'title',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('farposts_preview', 'title',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=70),
               existing_nullable=True)
    # ### end Alembic commands ###
