"""init

Revision ID: c3f60658f41c
Revises: 
Create Date: 2024-07-31 11:37:27.268401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3f60658f41c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farposts_preview',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=70), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('farposts_preview')
    # ### end Alembic commands ###
